version: "2.0"
services:
    # the server with the mssql master db and mssql copy db
    database:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "<YourNewStrong@Passw0rd>"
        ports:
            - "1433:1433"

    # the php script to create a zip archive of diff between masterDB and copyDB
    app:
        build: ./local-server
        volumes:
            - ./local-server/src:/app/src
        environment:
            MASTER_DB_HOST: database
            MASTER_DB_NAME: origin
            MASTER_DB_USER: sa
            MASTER_DB_PASSWORD: <YourNewStrong@Passw0rd>
            COPY_DB_NAME: copy
            SFTP_HOST: destination_server
            SFTP_PORT: 22
            SFTP_REMOTE_PATH: delta.zip
            SFTP_USER: test
            SFTP_PASSWORD: testpassword
            PROCESS_OUTPUT_URL: http://destination_server:5050/webService.php
        depends_on:
            - "database"

    # the server running postgress and a SFTP server
    # this also has a web service running to trigger the
    # processing of SFTP upload into postgres DB
    destination_server:
        build: ./destination-server
        restart: always
        volumes:
            - ./destination-server/src:/sync-app
        environment:
            # for postgress docker config
            POSTGRES_PASSWORD: password
            # for target postgress server
            TARGET_POSTGRES_HOST: 127.0.0.1
            TARGET_POSTGRES_DB_NAME: publishing
            TARGET_POSTGRES_USER: postgres
            TARGET_POSTGRES_PASSWORD: password
        ports:
            - 5050:5050
            - 5432:5432
