version: "2.0"
services:
  database:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourNewStrong@Passw0rd>"
    ports:
      - "1433:1433"

  app:
    image: "lbosqmsft/mssql-php-msphpsql"
    volumes:
      - ./src:/app
    command: "php /app/test.php"
    environment:
      MASTER_DB_HOST: database
      MASTER_DB_NAME: origin
      MASTER_DB_USER: sa
      MASTER_DB_PASSWORD: <YourNewStrong@Passw0rd>
      COPY_DB_NAME: copy
    depends_on:
      - "database"
